Source/CustomerApplication/CustomerApplication/Controllers/MessageController.cs
using AutoMapper;
using Message.Facade;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Message.Facade.DTOs;

namespace CustomerApplication.Controllers
{
    public class MessageController : Controller
    {
        private IMessageFacade messageFacade;

        private IMapper mapper;
        private MapperConfiguration MapConfig;

        public MessageController()
        {
            this.messageFacade = new MessageFacade();
            var mapConfig = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<MessagesDTO, ViewModels.MessagesVM>();
            });
            mapper = mapConfig.CreateMapper();
        }

        public MessageController(IMessageFacade messageFacade)
        {
            this.messageFacade = messageFacade;
            var mapConfig = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<MessagesDTO, ViewModels.MessagesVM>();
            });
            mapper = mapConfig.CreateMapper();
        }


        // GET: Message
        public ActionResult Index(string recipientID)
        {
            var v = messageFacade.getMessages(recipientID).Select(m => mapper.Map<MessagesDTO, ViewModels.MessagesVM>(m)).ToList();
            if (v != null)
            {
                return View(v);
            }
            return RedirectToAction("Index", "Home");
            }


        public ActionResult deleteMessage(int id)
        {
            MessageIdDTO messageID = new MessageIdDTO()
            {
                MessageID = id
            };
            messageFacade.deleteMessage(messageID);

            return RedirectToAction("Index");
        }
            

        }

    }

Source/CustomerApplication/CustomerApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li> @*First field is text shown on webpage, second is the method called and third is controller the method is called in*@
                    <li>@Html.ActionLink("Warehouse", "Index", "Warehouse")</li>
                    <li>@Html.ActionLink("Orders", "OrderHistory", "Warehouse", new { userName = User.Identity.Name }, null)</li>
                    <li>@Html.ActionLink("Messages", "Index", "Message", new { recipientID = User.Identity.Name }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>